server:
  port: 9000
spring:
  main:
    web-application-type: reactive
  application:
    name: miniTT-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: miniTT-user
          uri: lb://miniTT-user/api/miniTT/user/**
          predicates:
            - Path=/api/miniTT/user/**

# 开启日志
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
