server:
  port: 9000
spring:
  application:
    name: miniTT-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: miniTT-user
          uri: lb://miniTT-user/api/miniTT/user/**
          predicates:
            - Path=/api/miniTT/user/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/miniTT/user/v1/user/login
                  - /api/miniTT/user/v1/user/has-username
# 开启日志
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
